[package]
name = "graphics_rgz"
version = "0.1.0"
edition = "2021"

[dependencies]
gl = { path="gl" }
winit = "0.28.4"
glutin = "0.30.7"
gl_window_provider = { path="gl_window_provider" }
glam = "0.24.0"
